enum ExcelTypes {
  GET_TABLE = 'GET_TABLE',
  SET_ERROR = 'SET_ERROR',
  SAVE_TABLE = 'SAVE_TABLE',
  APPLY_STYLE = 'APPLY_STYLE',
  DELETE_TABLE = 'DELETE_TABLE',
  CHANGE_TITLE = 'CHANGE_TITLE',
  TABLE_RESIZE = 'TABLE_RESIZE',
  CHANGE_STYLES = 'CHANGE_STYLE',
  CHANGE_CONTENT = 'CHANGE_CONTENT',
  UPDATE_FORMULA = 'UPDATE_FORMULA',
  UPDATE_OPENED_DATE = 'UPDATE_OPENED_DATE',
}

export default ExcelTypes;
